# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'doof' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for doof
  pod 'UICircularProgressRing'

end

target 'doof WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for doof WatchKit App

end

target 'doof WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for doof WatchKit Extension

end
